### ISSUE TITLE
Channel-join after creating new channel in Discord broken (for me)

### ISSUE THREAD

**Issue by edfletcher** [edfletcher/drc#5]
`shoky` kindly noted in the IRC channel that it's working fine for them, but when trying to join them in #drc (because #discordrc throws errors saying "discord not allowed in name": need to file a bug for that too!) the UI makes it seem like joining worked fine but no messages came through. After enabling debug logging and trying again I managed to catch this:

```
drc-discord-1  | 2022-12-22T00:12:14.857Z [debug] REG'ed OTH for irc:responseJoinChannel discrim drc
drc-irc-1      | 2022-12-22T00:12:14.865Z [error] bad Redis msg TypeError: Cannot read properties of undefined (reading 'name')
drc-irc-1      |     at getChannelJoinFunc (/usr/src/drc/irc/ipcMessage.js:31:54)
drc-irc-1      |     at module.exports (/usr/src/drc/irc/ipcMessage.js:208:24)
drc-irc-1      |     at runMicrotasks (<anonymous>)
drc-irc-1      |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {"type":"discord:requestJoinChannel:irc","data":{"name":"drc","id":"1055276387918946404","parentId":"911345720680939530"}}
drc-irc-1      | 2022-12-22T00:12:14.865Z [debug] Redis msg! drc-dev {"type":"irc:responseJoinChannel","data":{"name":"drc","id":"1055276387918946404","parentId":"911345720680939530"}}
```

**Comment by edfletcher** [comment]
FA'ed this and indeed that failure mode matches the [race condition described by this comment](https://github.com/edfletcher/drc/blob/main/irc/ipcMessage.js#L242-L245). _Really_ need to fix that, so not closing this but retitling to more-correctly describe the failure mode.
